name: Test & Release

on:
  pull_request:
  push:

jobs:
  tests:
    name: Test & Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Host
        run: sudo apt update && sudo apt install -y libphysfs-dev emscripten
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Deps
        run: nimble install -d -y
      - name: Build Carts
        run: nimble carts
      - name: Run unit-tests
        run: nimble test --passC:"-Ivendor/"
      - name: Build Libretro - Linux x86_64
        run: nimble libretro && mv libnull0_libretro.so null0_libretro.so && zip libretro-linux-x86_64.zip -r null0_libretro.so
      - name: Build Runtime - Linux x86_64
        run: nimble runtime && zip runtime-linux-x86_64.zip -r null0
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.null0
            *-*-*.zip
