name: Test

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install -y libphysfs-dev emscripten
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v4
      - run: nimble install -y
      - run: nimble carts
      - run: nimble test